# ui.py
from streamlit_ui import (
    MetricDisplay,
    ChartDisplay,
    TableDisplay,
    display_tab1_header,
    display_tab1_metrics,
    display_tab1_bep,
    display_tab1_chart,
    display_tab1_analysis,
    display_tab1,
    display_tab2_header,
    display_tab2_basic_forecast,
    display_tab2_ml_forecast,
    display_tab2_monte_carlo,
    display_tab3_header,
    display_tab3_bep_info,
    display_tab3_monthly_bep,
    display_tab3_sensitivity,
    display_tab4_header,
    display_tab4_area_metrics,
    display_tab4_storage_table,
    display_tab4_profit_table,
    display_tab4_results,
    compare_params,
)